### ISSUE TITLE
option to go to shell

### ISSUE THREAD

**Issue by condoratberlin** [kedder/openvario-shell#1]
Currently i find no option to go to the shell on the Openvario.

**Comment by kedder** [comment]
Not true, exit menu has "Shell" option. Just press X (esc) button in main menu and pick "Shell".

The screen is not properly cleared though, that's a bug.

**Comment by condoratberlin** [comment]
I'm soory, just found it now.

**Comment by kedder** [comment]
NP, thanks for using it! :)
