### ISSUE TITLE
Menu to set wlan connection

### ISSUE THREAD

**Issue by condoratberlin** [kedder/openvario-shell#3]
It would be great if an interface for a wlan connection could be implemented. to establish wlan connections on field.

**Comment by condoratberlin** [comment]
May be it is possible to use an existing interface to connman. There is a python package [pyconnman](https://github.com/liamw9534/pyconnman) which uses dbus as interface to connman.

**Comment by kedder** [comment]
I'm pretty sure it is possible, but I didn't research this topic yet. Mostly because connecting to wlan is a one time activity - connect once and wifi is remembered forever, so low on my personal priority list. pyconnman looks like the way to go, if it still works.

**Comment by kedder** [comment]
Done, pending for the next release

**Comment by condoratberlin** [comment]
Hi, thanks a lot again for this menu!!!!

It works in general, but sometimes while scaning the process failed and returned to the console as shown on the following picture:
![IMG_20210327_133107](https://user-images.githubusercontent.com/49398997/112722435-de2e8380-8f09-11eb-9613-8b491e42675f.jpg)

I hope this helps to figure out the issue.

**Comment by kedder** [comment]
Hm, thanks, the traceback is useful.

What version of openvario-shell do you have? The version is visible on the main menu screen.

**Comment by kedder** [comment]
Nevermind, I see the version in a traceback.

**Comment by kedder** [comment]
I've just released 0.7.3 which should fix this crash. Thanks for reporting it!
