### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by Blaubart** [kedder/openvario-shell#32]
Hi Andrey, I have another idea. What do you think of an installation script for the menu. The commands that you have to issue are quite long. If you write a script that is in the .xcsoar folder and is backed up with the data backup, I only need one command. That would be very convenient. Another uninstall script would also be helpful.

**Comment by kedder** [comment]
My plan was eventually merge openvario shell into the official image, so that you don't need to install it at all. I think now it covers all the features of the old menu, we can more or less go forward with it. I just need a bit more real-life testing from volunteers to ensure it is stable enough.

Install script might help a bit with that, but you still need a working network connection for it to be useful, and that is not an easy thing to set up without experience in the old menu.

**Comment by kedder** [comment]
@Blaubart, actually, do you mean a script that you would run yourself on command line shell? I could probably make it one command, but it will look like
 
```sh
wget https://raw.githubusercontent.com/kedder/openvario-shell/master/scripts/ovshell-install.sh -O - | sh
```

Still a bunch of stuff to type. Do you think that would help?

**Comment by Blaubart** [comment]
Hi Andrey,

Yes, I meant a script that I load onto the OV in the .xcsoar folder using the USB stick, for example. This folder is backed up by the backup. If I now install a new image, I move this folder back onto the SD card and with a command, such as OpenVario-shell install, I can install it again directly. At the moment I change my image a lot because we are still working on getting ADS-B in OV. It is exhausting to always enter the long command by hand ;-)

Regards
Dirk

**Comment by kedder** [comment]
Oh, ok, I can do that pretty easily.

**Comment by Blaubart** [comment]
Hi Andrey,

that sounds good!
> I just need a bit more real-life testing from volunteers to ensure it is stable enough.

I will test it at my plane and I will install the menu at our DuoDiscus from the club. So if I find something thats not working, I will, send you a message.

Regards
Dirk

**Comment by OBrown92** [comment]
I will test it too. Have an OpenVario on my desk at the moment.

**Comment by kedder** [comment]
Ok, you can download the scripts:

* Install: https://raw.githubusercontent.com/kedder/openvario-shell/master/scripts/openvario-shell-install.sh
* Uninstall: https://raw.githubusercontent.com/kedder/openvario-shell/master/scripts/openvario-shell-uninstall.sh
