### ISSUE TITLE
Copy files from USB stick directly to /home/root/.xcsoar

### ISSUE THREAD

**Issue by DanD222** [kedder/openvario-shell#38]
At present, the Backup feature copies files from the USB stick to the home (?) directory.

What do you think about having the option to copy files directly to the /home/root/.xcsoar directory, so that no further copying/moving is needed in the shell?

**Comment by kedder** [comment]
Not sure I understand the issue. What moving/copying do you think is needed? Backup (restore) copies from USB stick to root filesystem, not to the home. 

Restore should place all the files to locates they were during backup.

**Comment by DanD222** [comment]
Sorry, I meant Restore :(

Say I have a waypoints file, or a preferences file, that I want to transfer to an OpenVario device using a USB stick. These files weren’t on OpenVario to begin with, and they are now in the root directory on my USB stick.

The Restore function copies my files from the USB stick to the root file system. In order for XCSoar to be able to use the files, I need to exit to shell and manually copy the files to /home/root/.xcsoar.

My idea is of a “Copy to XCSoar directory” button/function, which would copy the files from the USB stick directly to /home/root/.xcsoar, rather than to the root filesystem.

**Comment by kedder** [comment]
The intention was to make a backup first, and then you would have a partial filesystem on your usb stick, that you can modify on your PC. The XCSoar directory would be in `openvario/backup/home/.xcsoar` on your stick after the backup. 

After restoring that edited backup, files would be transferred back to openvario. OVShell would not even touch files on the root of your USB stick (because who knows what you have put there), it will only use files in `openvario/backup` directory on USB stick.

**Comment by DanD222** [comment]
Ah, OK. I didn’t have a USB stick with the OV filesystem. The files were actually copied from the USB stick root directory to the OV root directory, but I was expecting that, so I didn’t put a lot of files there to begin with.

It’d be nice if one could just grab any old USB stick and use it without sticking it in an OV unit first, select just the files one wants to copy and move them to the XCSoar directory, but I’m not sure if it’s worth the effort to go  down an almost-full-blown-file-manager route.

What happens when the files that are on OV are not on the USB stick (assuming I’ve created the OV file system first using Backup) - I’m assuming the files on OV are not touched? Is the file modification date taken into account somehow (so that newer preference files on OV are not overwritten for example)?

**Comment by kedder** [comment]
OVShell just simply copies all files from `openvario/backup` on USB stick to `/` on OV device, overwriting files if filename matches. No magic. It just uses rsync for that to speed up things. I did not check specifically if modification date is taken into account or not, but I expect not to (I'd consider it a bug if modification time affects something).

**Comment by DanD222** [comment]
OK, thanks for the clarification. I’ve tried Backup / Restore  - that took a while for everything to be copied, plus the .xcsoar folder was hidden on the USB drive, so this route wasn’t particularly practical for me. 

I guess if you feel like maybe using the file picker code that’s used for the log download and have it copy the selected files from the USB stick root directory to /home/root/.xcsoar then that’d be a “nice to have” feature, but it’s not something one can’t live without.. so I’ll close this now.
