### ISSUE TITLE
error when installing: wget: not an http or ftp url: https://raw.githubusercontent.com/kedde ... install.sh

### ISSUE THREAD

**Issue by rdevries1965** [kedder/openvario-shell#66]
I have a connection with my Cubieboard and PC via bitvise which works fine. I can browse thru the data folders of the Cubieboard on my pc. 
On my PC i copied the OV Shell install line and pasted in the shell of the Cubieboard and executed it.
I get an error: wget: not an http or ftp url: https://raw.githubusercontent.com/kedde ... install.sh

I triple checked the command line. On a different OV lat week it worked.

Any idea if this is related to OV-shell ?

**Comment by kedder** [comment]
Ugh, sorry I missed this completely. Not sure if this is still relevant, but for whatever reason your `wget` can't read from `https` urls. Not completely sure why, on the latest released openvario image wget can do this. I'm closing this now, but feel free to reopen if it still relevant, I'll try to help you with this.
