### ISSUE TITLE
Unable to install compan via opkg: missing python3-charset-normalizer-2.0.9

### ISSUE THREAD

**Issue by lordfolken** [kedder/openvario-shell#96]
I tried to install openvario-compman with opkg install openvario-compman

It complains that the python3-charset-normalizer 2.0.9 isn't available.

**Comment by lordfolken** [comment]
![Uploading IMG_20220101_155947.jpg…]()

**Comment by kedder** [comment]
I have re-uploaded the PPA, it should include `python3-charset-normalizer` as well. However, with so many changes to openvario image recently, I can't be sure everything will work as before (they still might though) :) Things need to settle a bit.
